// ============================================================================
// EXAMPLE OUTPUT — Generated by @csharp-class-generator
//
// User input:
//   controller.name           = WeatherForecast
//   actions                   = GetAll, GetById, Create
//   controller.dependencies.pattern = Service
//
// Resolved by semantic-elevation rules:
//   namespace                 = MyCompany.MyProduct.Api.Controllers  (default)
//   controller.routeBase      = api/weather-forecasts                (pluralize + kebab-case)
//   controller.dependencies.serviceInterface = IWeatherForecastService (defaulting rule)
//   actions[0].httpVerb       = GET    (inferred from "GetAll")
//   actions[1].httpVerb       = GET    (inferred from "GetById")
//   actions[1].route          = {id}   (route param detected)
//   actions[2].httpVerb       = POST   (inferred from "Create")
//   dtos.block                = auto-generated records
// ============================================================================

using Microsoft.AspNetCore.Mvc;

namespace MyCompany.MyProduct.Api.Controllers;

[ApiController]
[Route("api/weather-forecasts")]
public sealed class WeatherForecastController : ControllerBase
{
    private readonly IWeatherForecastService _service;

    public WeatherForecastController(IWeatherForecastService service)
    {
        _service = service;
    }

    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<WeatherForecastDto>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<WeatherForecastDto>>> GetAll()
    {
        var result = await _service.GetAllAsync();
        return Ok(result);
    }

    [HttpGet("{id}")]
    [ProducesResponseType(typeof(WeatherForecastDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<WeatherForecastDto>> GetById([FromRoute] int id)
    {
        var result = await _service.GetByIdAsync(id);
        if (result is null)
            return NotFound();

        return Ok(result);
    }

    [HttpPost]
    [ProducesResponseType(typeof(WeatherForecastDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<WeatherForecastDto>> Create([FromBody] CreateWeatherForecastRequest request)
    {
        var result = await _service.CreateAsync(request);
        return CreatedAtAction(nameof(GetById), new { id = result.Id }, result);
    }
}

public record WeatherForecastDto(int Id, string Summary, int TemperatureC, DateOnly Date);

public record CreateWeatherForecastRequest(string Summary, int TemperatureC, DateOnly Date);
