// ============================================================================
// EXAMPLE OUTPUT — Generated by @csharp-class-generator with:
//   entityName        = WeatherForecast
//   namespace         = MyApi.Controllers       (semantic retrieval from folder)
//   route             = api/[controller]         (default)
//   actions           = GetAll,GetById,Create    (user-provided)
//   idType            = int                      (default)
//   dtoName           = WeatherForecastDto       (default)
//   createRequestName = CreateWeatherForecastRequest (default)
//   serviceName       = IWeatherForecastService  (default)
// ============================================================================

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MyApi.Controllers;

/// <summary>
/// API endpoints for managing WeatherForecast resources.
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class WeatherForecastController : ControllerBase
{
    private readonly ILogger<WeatherForecastController> _logger;
    private readonly IWeatherForecastService _service;

    public WeatherForecastController(
        ILogger<WeatherForecastController> logger,
        IWeatherForecastService service)
    {
        _logger = logger;
        _service = service;
    }

    // ── GetAll ────────────────────────────────────────────
    /// <summary>
    /// Retrieves all WeatherForecast resources.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<WeatherForecastDto>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<WeatherForecastDto>>> GetAll()
    {
        var items = await _service.GetAllAsync();
        return Ok(items);
    }

    // ── GetById ───────────────────────────────────────────
    /// <summary>
    /// Retrieves a single WeatherForecast by its identifier.
    /// </summary>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(WeatherForecastDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<WeatherForecastDto>> GetById(int id)
    {
        var item = await _service.GetByIdAsync(id);
        if (item is null)
            return NotFound();

        return Ok(item);
    }

    // ── Create ────────────────────────────────────────────
    /// <summary>
    /// Creates a new WeatherForecast.
    /// </summary>
    [HttpPost]
    [ProducesResponseType(typeof(WeatherForecastDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<WeatherForecastDto>> Create([FromBody] CreateWeatherForecastRequest request)
    {
        if (!ModelState.IsValid)
            return BadRequest(ModelState);

        var created = await _service.CreateAsync(request);
        return CreatedAtAction(nameof(GetById), new { id = created.Id }, created);
    }
}
